[postgres]
driver = "asyncpg"
host = "postgres"
port = 5432
user = "postgres"
password = "postgres"
database = "postgres"

[logging]
level = "INFO"

[sqlalchemy]
echo = false
echo_pool = false
pool_size = 5
max_overflow = 10